# Generated by Django 2.2.16 on 2024-01-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_follow'),
        ('posts', '0004_auto_20240110_0002'),
    ]

    operations = [
    ]
